import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from './theme-provider';
import Header from '@components/custom/Header';
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes/dist/themes/src/themes';
import ConvexClientProvider from "./ConvexClientProvider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <ConvexClientProvider>
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
              <Header />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
    </ConvexClientProvider>
  );
}


